CREATE DATABASE DEVAPP;
CREATE USER 'developer'@'localhost' IDENTIFIED BY '<PASSOWRD>';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'developer'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
